export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_TWO_STEP_REQUEST = 'LOGIN_TWO_STEP_REQUEST';
export const LOGIN_TWO_STEP_SUCCESS = 'LOGIN_TWO_STEP_SUCCESS';
export const LOGIN_TWO_STEP_FAILURE = 'LOGIN_TWO_STEP_FAILURE';

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const SEND_VERIFICATION_OTP_REQUEST = "SEND_VERIFICATION_OTP_REQUEST";
export const SEND_VERIFICATION_OTP_SUCCESS = "SEND_VERIFICATION_OTP_SUCCESS";
export const SEND_VERIFICATION_OTP_FAILURE = "SEND_VERIFICATION_OTP_FAILURE";

export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST = "ENABLE_TWO_STEP_AUTHENTICATION_REQUEST";
export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS = "ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS";
export const ENABLE_TWO_STEP_AUTHENTICATION_FAILURE = "ENABLE_TWO_STEP_AUTHENTICATION_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const SEND_RESET_PASSWORD_OTP_REQUEST = "SEND_RESET_PASSWORD_OTP_REQUEST";
export const SEND_RESET_PASSWORD_OTP_SUCCESS = "SEND_RESET_PASSWORD_OTP_SUCCESS";
export const SEND_RESET_PASSWORD_OTP_FAILURE = "SEND_RESET_PASSWORD_OTP_FAILURE";

export const VERIFY_RESET_PASSWORD_OTP_REQUEST = "VERIFY_RESET_PASSWORD_OTP_REQUEST";
export const VERIFY_RESET_PASSWORD_OTP_SUCCESS = "VERIFY_RESET_PASSWORD_OTP_SUCCESS";
export const VERIFY_RESET_PASSWORD_OTP_FAILURE = "VERIFY_RESET_PASSWORD_OTP_FAILURE";

export const LOGOUT="LOGOUT";
