// actionTypes.js

// Action types for getting user wallet
export const GET_USER_WALLET_REQUEST = 'GET_USER_WALLET_REQUEST';
export const GET_USER_WALLET_SUCCESS = 'GET_USER_WALLET_SUCCESS';
export const GET_USER_WALLET_FAILURE = 'GET_USER_WALLET_FAILURE';

export const GET_WALLET_TRANSACTION_REQUEST = 'GET_WALLET_TRANSACTION_REQUEST';
export const GET_WALLET_TRANSACTION_SUCCESS = 'GET_WALLET_TRANSACTION_SUCCESS';
export const GET_WALLET_TRANSACTION_FAILURE = 'GET_WALLET_TRANSACTION_FAILURE';

// Action types for depositing money
export const DEPOSIT_MONEY_REQUEST = 'DEPOSIT_MONEY_REQUEST';
export const DEPOSIT_MONEY_SUCCESS = 'DEPOSIT_MONEY_SUCCESS';
export const DEPOSIT_MONEY_FAILURE = 'DEPOSIT_MONEY_FAILURE';

// Action types for transferring money
export const TRANSFER_MONEY_REQUEST = 'TRANSFER_MONEY_REQUEST';
export const TRANSFER_MONEY_SUCCESS = 'TRANSFER_MONEY_SUCCESS';
export const TRANSFER_MONEY_FAILURE = 'TRANSFER_MONEY_FAILURE';


