export const FETCH_COIN_LIST_REQUEST = 'FETCH_COIN_LIST_REQUEST';
export const FETCH_COIN_LIST_SUCCESS = 'FETCH_COIN_LIST_SUCCESS';
export const FETCH_COIN_LIST_FAILURE = 'FETCH_COIN_LIST_FAILURE';

export const FETCH_TOP_50_COINS_REQUEST = 'FETCH_TOP_50_COINS_REQUEST';
export const FETCH_TOP_50_COINS_SUCCESS = 'FETCH_TOP_50_COINS_SUCCESS';
export const FETCH_TOP_50_COINS_FAILURE = 'FETCH_TOP_50_COINS_FAILURE';

export const FETCH_TRADING_COINS_REQUEST = 'FETCH_TRADING_COINS_REQUEST';
export const FETCH_TRADING_COINS_SUCCESS = 'FETCH_TRADING_COINS_SUCCESS';
export const FETCH_TRADING_COINS_FAILURE = 'FETCH_TRADING_COINS_FAILURE';

export const FETCH_MARKET_CHART_REQUEST = 'FETCH_MARKET_CHART_REQUEST';
export const FETCH_MARKET_CHART_SUCCESS = 'FETCH_MARKET_CHART_SUCCESS';
export const FETCH_MARKET_CHART_FAILURE = 'FETCH_MARKET_CHART_FAILURE';

export const FETCH_COIN_BY_ID_REQUEST = 'FETCH_COIN_BY_ID_REQUEST';
export const FETCH_COIN_BY_ID_SUCCESS = 'FETCH_COIN_BY_ID_SUCCESS';
export const FETCH_COIN_BY_ID_FAILURE = 'FETCH_COIN_BY_ID_FAILURE';

export const FETCH_COIN_DETAILS_REQUEST = 'FETCH_COIN_DETAILS_REQUEST';
export const FETCH_COIN_DETAILS_SUCCESS = 'FETCH_COIN_DETAILS_SUCCESS';
export const FETCH_COIN_DETAILS_FAILURE = 'FETCH_COIN_DETAILS_FAILURE';

export const SEARCH_COIN_REQUEST = 'SEARCH_COIN_REQUEST';
export const SEARCH_COIN_SUCCESS = 'SEARCH_COIN_SUCCESS';
export const SEARCH_COIN_FAILURE = 'SEARCH_COIN_FAILURE';